### ISSUE TITLE
응원합니다

### ISSUE THREAD

**Issue by Munbin-Lee** [pknu-wap/2022_2_WAP_APP_TEAM3#1]
화이팅

**Comment by jeongjaino** [comment]
화이팅입니다~ !!

**Comment by Redish03** [comment]
감사합니다~ㅎㅎ

**Comment by alstn113** [comment]
응원합니다
![abe406f214955aff04ac7f70aa4bd840](https://user-images.githubusercontent.com/75781414/206172875-5b2aec4b-dd73-412f-8866-bf53a0014142.gif)

**Comment by imiswest** [comment]
감솨합니다 !!~~~
